name: mqttsrv
version: 0.1
summary: An mqtt server that listens locally to 1883
description: mqtt server that listens to port 1883 locally
confinement: strict
grade: stable

apps:
    mqttsrv:
        command: mqttsrv $1
        daemon: simple
        plugs: [network-bind, network]
parts:
  mqttsrv:
    plugin: go
    source: src/mqttsrv
